
name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
    
    - run: chrome --version
    
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Test with Maven 
      run: mvn clean test
      
    - name: Test Reporter
      uses: dorny/test-reporter@v1.5.0
      with:
        name: Report
        path: target/surefire-reports/junitreports/TEST-tests.*.xml
        reporter: java-junit

